name: Deploy Medusa

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: medusa_db
          POSTGRES_USER: medusa_user
          POSTGRES_PASSWORD: chinni
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U medusa_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install cross-env
        run: npm install --save-dev cross-env

      - name: Install Medusa CLI
        run: npm install -g @medusajs/medusa-cli

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432 -U medusa_user; do sleep 1; done

      - name: Wait for Redis to be ready
        run: until redis-cli -h redis ping; do sleep 1; done

      - name: Run database migrations
        run: |
          medusa migrations run  # Runs migrations to set up your DB schema

      - name: Build and start Medusa server
        run: |
          npm run build
          npm run start
