name: Deploy Medusa

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install

      - name: Copy files to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  
          HOST: ${{ secrets.EC2_HOST }}              
          USER: ubuntu                                
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --exclude='node_modules' -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ $USER@$HOST:/home/ubuntu/medusa-store/

      - name: SSH into EC2 and start the application
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}  
          HOST: ${{ secrets.EC2_HOST }}              
          USER: ubuntu                                
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            cd /home/ubuntu/medusa-store/
            rm -rf node_modules
            npm install
            npm run clean
            npm run build
            npm run start
          EOF
