name: Deploy Medusa to ECS Fargate Spot

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose whether to apply or destroy Terraform resources'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Terraform environment
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      # Step 3: Terraform Init
      - name: Terraform Init
        working-directory: ./ecs-fargate
        run: terraform init

      # Step 4: Terraform Apply or Destroy
      - name: Terraform Apply/Destroy
        working-directory: ./ecs-fargate
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            echo "Applying Terraform changes..."
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            echo "Destroying Terraform resources..."
            terraform destroy -auto-approve
          else
            echo "Invalid action specified."
            exit 1
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1  # Ensure the region is set

      # Step 5: Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registries: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
          registry-type: private
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Use your AWS Access Key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Use your AWS Secret Access Key
          AWS_REGION: us-east-1  # Specify the AWS region

      # Step 6: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t medusa-app:latest .

      # Step 7: Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag medusa-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/medusa-app:latest

      # Step 8: Push Docker image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/medusa-app:latest

      # Step 9: Show Terraform Outputs (only if "apply" is selected)
      - name: Show Terraform Outputs
        if: ${{ github.event.inputs.action == 'apply' }}
        working-directory: ./ecs-fargate
        run: terraform output
