name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  # This triggers the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Updated to v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: false
          registry-type: private
          skip-logout: false

      - name: Create ECR Repository
        id: create_ecr
        run: |
          aws ecr create-repository --repository-name medusa-repo --region us-east-1 || echo "ECR repository already exists"

      - name: Build Docker Image
        run: |
          IMAGE_NAME=medusa-repo
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

      - name: Push Docker Image to ECR
        run: |
          IMAGE_NAME=medusa-repo
          # Tag and push the Docker image to ECR
          docker tag $IMAGE_NAME:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:$TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME:$TAG

      - name: Logout from ECR
        run: docker logout

